name: Deploy

on:
  push:
    branches:
      - master
      - main
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install dependencies
        run: npm install
      - name: bundle modules
        env:
          REACT_APP_DOMAIN: ${{secrets.REACT_APP_DOMAIN}}
          REACT_APP_REGION: ${{secrets.REACT_APP_REGION}}
          REACT_APP_USER_POOL_ID: ${{secrets.REACT_APP_USER_POOL_ID}}
          REACT_APP_USER_POOL_WEB_CLIENT_ID: ${{secrets.REACT_APP_USER_POOL_WEB_CLIENT_ID}}
          REACT_APP_REDIRECT_SIGN_IN: ${{secrets.REACT_APP_REDIRECT_SIGN_IN}}
          REACT_APP_REDIRECT_SIGN_OUT: ${{secrets.REACT_APP_REDIRECT_SIGN_OUT}}
          REACT_APP_RESPONSE_TYPE: ${{secrets.REACT_APP_RESPONSE_TYPE}}
          REACT_APP_SCOPE: ${{secrets.REACT_APP_SCOPE}}
          REACT_APP_IDENTITY_POOL_ID: ${{secrets.REACT_APP_IDENTITY_POOL_ID}}
        run: npm run build
      - name: set aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
      - name: deploy to s3
        run: aws s3 sync ./build/ s3://jtj-frontend
      - name: Print environment variables
        run: |
          echo "Environment variables:"
          env
env:
  CI: false
